name: Integración continua - API Usuarios

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Clonar el repositorio
        uses: actions/checkout@v3

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🧪 Ejecutar pruebas
        run: npm test

      - name: ✅ Verificar formato de código
        run: npx eslint . || true
